events {}

http {

    upstream frontend {
        server web-frontend-server1:80;
        server web-frontend-server2:80;
    }

    upstream backend {
        server application-backend-server:8081;
    }

    upstream keycloak {
        server authentication-identity-server:8080;
    }

    server {

        listen 80;

        location / {
            proxy_pass http://frontend;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location /api/ {
            proxy_pass http://backend/;
        }

        location /auth/ {
            proxy_pass http://keycloak/;
        }

        location /keycloak/ {
            proxy_pass http://keycloak/;
        }

    }

}